#!/bin/bash

if [[ -f tokens.csv ]]; then
	echo "Tokens already generated"
	exit
fi

token=$(openssl rand -hex 8)
uuid=$(uuidgen)
printf "%s,kubeadm-node-csr,%s,system:kubelet-bootstrap\n" "$token" "$uuid" > tokens.csv
